### ISSUE TITLE
Xcode 13 update

### ISSUE THREAD

**Issue by Adrimi** [CypherPoet/charmed-dark-xcode-theme#4]
Looks like Xcode 13 has brought some changes on how `Project Function and Method Names` are colored. 
I guess that it could not be something intended by the Xcode core team. 

Nevertheless, the result is that method parameter attributes are colored in the same way as the method name (see the word `using`): 
![image](https://user-images.githubusercontent.com/37190688/134492832-9341c33d-d800-4072-93b1-9161eef5959d.png)

Before it was in the same color as `Plain Text`:
![image](https://user-images.githubusercontent.com/37190688/134493135-b522686d-737e-4fb6-bb06-4110e50af9c8.png)

Just pointing out, there could be also more changes than that.

**Comment by CypherPoet** [comment]
Hey @Adrimi, thanks for pointing this out.

You're correct that this appears to be the result of `Project Function and Method Names` now apparently affecting both... well... the function and the method names 😄 .

There might be a way to separate these two -- but I wasn't able to see one within the settings available as of Xcode 14. As such, I'm going to keep it this way for now in https://github.com/CypherPoet/charmed-dark-xcode-theme/releases/tag/v3.1.0
